### PR TITLE
Fixed truncated rubrics in 'subject relationships' group

### PR DESCRIPTION
**Pull request by ricardofago**

### CODE REVIEW

**Comment by wolandscat** [comment]
@freshehr Ian - this pull request is needed - you missed a couple!

**Comment by ricardofago** [comment]
@wolandscat yes I checked it, just two quick remaining fixes, I guess: concept 8 was just "maternal" (judging from the near concepts, grandfather was truncated) and concept 36 had a trailing hyphen. See the [diff](https://github.com/openEHR/terminology/pull/3/files).

**Comment by wolandscat** [comment]
@ricardofago you quite right, sorry, didn't look close enough. Actually, I did the whole set of changes which did include these two, but Ian beat me to it, but obviously missed a couple. That will teach me...

**Comment by freshehr** [comment]
Thanks Ricardo - I missed those.

**Pull request merged**
